### ISSUE TITLE
Gradients not applying to Context Menu

### ISSUE THREAD

**Issue by NovalFuzzy** [LuckFire/GradientButtons#1]
Gradient Buttons **don't work on context menu**, however they **work with the Status Menu**. On the context menu, they **appear as bold** instead of having a gradient applied... Images are supplied below.

I could fix this myself, however you are the theme developer. I expect you to take insight into my issue and to push out a fix soon. teehee :) 

Gradient Buttons on Status Menu: (WORKING)
![image](https://user-images.githubusercontent.com/25520160/91214616-2eb9d600-e6c8-11ea-95e9-e9a5e454b51a.png)

Gradient Buttons on Context Menu: (NOT WORKING)
![image](https://user-images.githubusercontent.com/25520160/91214636-36797a80-e6c8-11ea-84ea-0ff0b5ee1c77.png)

**Comment by LuckFire** [comment]
It seems like you're using a different theme. Either disable your theme or send me the theme on Discord and I'll modify it to work. 
LuckFire#4800

**Comment by HooferDevelops** [comment]
i am having this issue as well.

**Comment by NovalFuzzy** [comment]
bad developer no star for you

**Comment by LuckFire** [comment]
kekw

**Comment by NovalFuzzy** [comment]
Thank you for reopening this issue. I have tried to send you a DM on Discord, however you don't accept messages from Server Members or non-friends. May you please accept my friend request? Fuzzy#0004

**Comment by NovalFuzzy** [comment]
You closed it.

**Comment by LuckFire** [comment]
Okay sent.

**Comment by HooferDevelops** [comment]
**why is it not working?**
