### ISSUE TITLE
Is it supposed to work on Mac?

### ISSUE THREAD

**Issue by TrueDanTDMfan** [LuckFire/GradientButtons#10]
This is not working on my Discord on mac, and yes I followed all the steps from others on the Discord Powercord Server.

**Comment by LuckFire** [comment]
weird, should work. can you provide more info on what steps you’ve taken as well as what themes/css snippets you use?

**Comment by TrueDanTDMfan** [comment]
Nice, its working now! Sorry for disturbing you!

**Comment by LuckFire** [comment]
no worries, glad you figured out what was wrong :>
