### ISSUE TITLE
PLEASE HELP WITH APPLYING GRADIENTS 

### ISSUE THREAD

**Issue by NovalFuzzy** [LuckFire/GradientButtons#5]
Hey there! You discarded my previous plea for help on your theme add-on. Please look at my previous issue linked below and let me know how we can resolve this :) 

https://github.com/LuckFire/GradientButtons/issues/1#issue-685708089

**Comment by NovalFuzzy** [comment]
WHY DID YOU CLOSE IT  ??????

**Comment by LuckFire** [comment]
:)
